name: Update Snapshots
on:
    pull_request: {}

jobs:
  test:
    name: Poison
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Craft bad artifact
      run: |
        mkdir artifact
        cd artifact
        mkdir HEAD
        touch HEAD/abc.png
    - name: Save Snapshot Artifact
      uses: actions/upload-artifact@v4
      with:
          name: bla
          path: artifact/
          retention-days: 1
